name: Docker Image

on:
  push:
    branches:
      - "main"
      - "testRunnerGithubAction"

jobs:
  docker:
    strategy:
      matrix:
        include:
          - model_name: stable-diffusion-v1-5
            model_tag: runwayml/stable-diffusion-v1-5
            model_url: https://huggingface.co/runwayml/stable-diffusion-v1-5

    runs-on: ubuntu-latest
    environment: runpodnqs-dockerhub
    steps:
      - name: Run Tests
        uses: direlines/runpod-test-runner@v1.1
        with:
          image-tag: ${{ secrets.DOCKERHUB_REPO }}/${{ secrets.DOCKERHUB_IMG }}:${{ matrix.model_name }}-dev
          runpod-api-key: ${{ secrets.RUNPOD_API_KEY }}
